apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openemr-dev

resources:
- ../../base
- configmap.yaml
- secrets.yaml
- nodeport-service.yaml

labels:
- pairs:
    environment: dev

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: OPENEMR_SETTING_site_addr_oath
        value: "https://openemr-dev.trancloud.work"
  target:
    kind: Deployment
    name: openemr
