apiVersion: v1
kind: Secret
metadata:
  name: openemr-secrets
  namespace: openemr-staging
type: Opaque
stringData:
  db_root_password: "ycm&17XK"
  db_user: "openemr_staging"
  db_password: "openemr_staging_pass_2024"
  oe_admin_user: "admin"
  oe_admin_password: "pass"
