apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openemr-sites-pvc
  labels:
    app: openemr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path  # k3s default storage class
